apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: fluentd
  name: fluentd-config
  namespace: server
data:
  fluent.conf: |
    global:
    <system>
        log_level info
    </system>    
    
    <source>
      @type  forward
      @id    input
      @label @mainstream
      port  24224
    </source>
    
    <source>
      @type http
      port 8888
      @label @mainstream
    </source>

    <source>
      type monitor_agent
      bind 0.0.0.0
      port 24220
    </source>

    <filter **>
      @type stdout
    </filter>
    
    <label @mainstream>
    
    <filter {sensor.**,fplug.**,wemo.**,hems.**}>
      @type typecast
      types temp:float,humi:float,lux:float,rain:float,pm10:float,pm25:float,pm40:float,pm100:float,uva:float,uvb:float,uvi:float,flow:float
    </filter>
    
    <match sensor>
      @type rewrite_tag_filter
      <rule>
        key     hostname
        pattern ESP32
        tag     sensor.esp32
      </rule>
      <rule>
        key     hostname
        pattern rasp
        tag     sensor.rasp
      </rule>
      <rule>
        key     hostname
        pattern rpi-cm4
        tag     sensor.rasp
      </rule>
    </match>
    
    <filter {sensor.esp32,fplug.**,wemo.**}>
      @type record_transformer
      enable_ruby
      renew_time_key self_time
      auto_typecast
      enable_ruby
      <record>
        self_time ${Time.now.to_i - record["self_time"].to_i }
      </record>
    </filter>
    
    <match {sensor.**,fplug.**,wemo.**,hems.**}>
      @type influxdb2
      url             http://proxy.green-rabbit.net:8086
      use_ssl         false
      token           "#{ENV['INFLUXDB_TOKEN']}"
      bucket          sensor
      org             home
      tag_keys        ["hostname"]
      time_precision  s
      <buffer>
        flush_interval  10
      </buffer>
    </match>
    
    <match test.**>
      @type influxdb2
      url             http://192.168.4.2:8086
      use_ssl         false
      token           "#{ENV['INFLUXDB_TOKEN']}"
      bucket          test
      org             home
      tag_keys        ["hostname"]
      time_precision  s
      <buffer>
        flush_interval  1
      </buffer>
    </match>
    
    <match fluent.{info,warn,error}>
      @type stdout
    </match>
    
    <match *.**>
      @type stdout
    </match>
    
    </label>
---
kind: Service
apiVersion: v1
metadata:
  name: fluentd
  namespace: server
  annotations:
    metallb.universe.tf/address-pool: default
    external-dns.alpha.kubernetes.io/hostname: fluentd.kubernetes.green-rabbit.net
spec:
  selector:
    app: fluentd
  ports:
  - name: fluentd
    port: 24224
    targetPort: 24224
  - name: fluentd-www
    port: 8888
    targetPort: 8888
  - name: monitor
    port: 24220
    targetPort: 24220
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd
  namespace: server
  labels:
    app: fluentd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
      - name: fluentd
        image: registry.green-rabbit.net/library/fluentd-custom:latest
        args:
        - --config
        - /etc/fluentd/fluent.conf
        env:
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: influxdb-token
              key: password
        volumeMounts:
        - name: config
          mountPath: /etc/fluentd
        ports:
          - containerPort: 24224
          - containerPort: 8888
          - containerPort: 24220
        resources:
          requests:
            memory: 128Mi
          limits:
            memory: 256Mi
        livenessProbe:
          httpGet:
            port: 24220
            path: /api/plugins
          initialDelaySeconds: 120
          periodSeconds: 60
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: config
        configMap:
          name: fluentd-config
      dnsPolicy: Default
      nodeSelector:
        kubernetes.io/hostname: database
