kind: Namespace
apiVersion: v1
metadata:
  name: bot
  labels:
    name: bot
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-bot-mercari-inventory-control
  namespace: bot
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  local:
    path: /home/kimata/github/mercari_bot/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - tanzania
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-bot-mercari-inventory-control
  namespace: bot
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: bot-mercari-inventory-control-deployment
  namespace: bot
  labels:
    app: bot-mercari-inventory-control
spec:
  # NOTE: kubeadm でセットアップした場合，基本的にタイムゾーンは UTC となるの注意
  # https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/
  schedule: "0 9 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bot-mercari-inventory-control
            image: registry.green-rabbit.net/library/bot_mercari_inventory_control:latest
            imagePullPolicy: Always
            volumeMounts:
            - mountPath: /opt/mercari_bot/data
              name: data
            resources:
              requests:
                memory: 320Mi
              limits:
                memory: 512Mi
          restartPolicy: Never
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: pvc-bot-mercari-inventory-control
          dnsPolicy: Default
          nodeSelector:
            kubernetes.io/hostname: tanzania
