apiVersion: apps/v1
kind: Deployment
metadata:
  name: wattmeter-sharp
  namespace: hems
  labels:
    app: wattmeter-sharp
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wattmeter-sharp
  template:
    metadata:
      labels:
        app: wattmeter-sharp
    spec:
      volumes:
      - name: dev
        hostPath:
          path: /dev/ttyUSB0
      containers:
      - name: wattmeter-sharp
        image: registry.green-rabbit.net/library/wattmeter_sharp:latest
        imagePullPolicy: Always
        env:
        livenessProbe:
          exec:
            command:
              - /opt/wattmeter_sharp/src/healthz.py
          initialDelaySeconds: 120
          periodSeconds: 60
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /dev/ttyUSB0
            name: dev
      dnsPolicy: Default
      nodeSelector:
        kubernetes.io/hostname: hems
