apiVersion: apps/v1
kind: Deployment
metadata:
  name: router-fan-deployment
  namespace: hems
  labels:
    app: router-fan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router-fan
  template:
    metadata:
      labels:
        app: router-fan
    spec:
      containers:
      - name: router-fan
        image: registry.green-rabbit.net/library/hems_router_fan:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: 32Mi
          limits:
            memory: 64Mi
        livenessProbe:
          exec:
            command:
              - /opt/yamaha_usb_ctrl/src/healthz.py
          initialDelaySeconds: 120
          periodSeconds: 60
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
      dnsPolicy: Default
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/server
                    operator: In
                    values:
                      - hems
