kind: Namespace
apiVersion: v1
metadata:
  name: panel
  labels:
    name: panel
---
kind: Namespace
apiVersion: v1
metadata:
  name: bot
  labels:
    name: bot
---
kind: Namespace
apiVersion: v1
metadata:
  name: bot
  labels:
    name: bot
---
kind: Namespace
apiVersion: v1
metadata:
  name: hems
  labels:
    name: hems
---
