apiVersion: apps/v1
kind: Deployment
metadata:
  name: m5paper-aqua-panel-deployment
  namespace: panel
  labels:
    app: m5paper-aqua-panel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m5paper-aqua-panel
  template:
    metadata:
      labels:
        app: m5paper-aqua-panel
    spec:
      containers:
      - name: m5paper-aqua-panel
        image: registry.green-rabbit.net/library/m5papere_aqua_panel:latest
        imagePullPolicy: Always
        env:
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: influxdb-token
              key: password
        resources:
          requests:
            memory: 128Mi
          limits:
            memory: 256Mi
        # livenessProbe:
        #   exec:
        #     command:
        #       - /opt/weather_panel/src/healthz.py
        #   initialDelaySeconds: 120
        #   periodSeconds: 60
        #   timeoutSeconds: 1
        #   successThreshold: 1
        #   failureThreshold: 3
      dnsPolicy: Default
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/server
                    operator: In
                    values:
                      - large

