apiVersion: apps/v1
kind: Deployment
metadata:
  name: m5paper-aqua-panel-deployment
  namespace: panel
  labels:
    app: m5paper-aqua-panel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m5paper-aqua-panel
  template:
    metadata:
      labels:
        app: m5paper-aqua-panel
    spec:
      containers:
      - name: m5paper-aqua-panel
        image: registry.green-rabbit.net/library/m5paper_aqua_panel:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5555
        env:
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: influxdb-token
              key: password
        resources:
          requests:
            memory: 128Mi
          limits:
            memory: 256Mi
        livenessProbe:
          httpGet:
            port: 5555
            path: /aqua-monitor/
          initialDelaySeconds: 120
          periodSeconds: 120
          timeoutSeconds: 30
          successThreshold: 1
          failureThreshold: 3
      dnsPolicy: Default
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/server
                    operator: In
                    values:
                      - large

