apiVersion: apps/v1
kind: Deployment
metadata:
  name: kindle-weather-panel-deployment
  namespace: panel
  labels:
    app: kindle-weather-panel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kindle-weather-panel
  template:
    metadata:
      labels:
        app: kindle-weather-panel
    spec:
      containers:
      - name: kindle-weather-panel
        image: registry.green-rabbit.net:5000/kimata/kindle_weather_panel:latest
        imagePullPolicy: Always
        env:
        - name: KINDLE_HOSTNAME
          value: 192.168.0.102
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: influxdb-token
              key: password
        resources:
          requests:
            memory: 128Mi
          limits:
            memory: 256Mi
        livenessProbe:
          exec:
            command:
              - /opt/kindle_weather/src/healthz.py
          initialDelaySeconds: 120
          periodSeconds: 60
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
      dnsPolicy: Default
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/server
                    operator: In
                    values:
                      - large
